name: amazmart
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.14
  cached_network_image: ^3.4.1
  awesome_snackbar_content: ^0.1.4
  dropdown_search: ^6.0.1
  dio: ^5.7.0
  retrofit: ^4.4.1
  json_annotation: ^4.9.0
  retrofit_generator: ^9.1.4
  build_runner: ^2.4.13
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.3.3
  flutter_rating_bar: ^4.0.1
  responsive_grid_list: ^1.4.0
  json_serializable: ^6.8.0
  custom_network_image: ^0.0.3
  path: ^1.9.0
  sqflite: ^2.4.1
  collection: ^1.18.0
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^8.0.1
  flutter_launcher_icons: ^0.14.2
  html_unescape: ^2.0.0
  # flutter_app_settings: ^0.0.2
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
  
  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost_Black.ttf
          weight: 500
        - asset: assets/fonts/Jost_Bold.ttf
          weight: 600
        - asset: assets/fonts/Jost_Regular.ttf
          weight: 400
        - asset: assets/fonts/Jost_Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost_SemiBold.ttf
          weight: 700
    
    - family: Noto
      fonts:
        - asset: assets/fonts/noto_serif_tamil_slanted.ttf
          weight: 500


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"  # Path to your app icon image
  adaptive_icon_background: "#FFFFFF"    # (Optional) Background color for Android adaptive icons
  adaptive_icon_foreground: "assets/icon/app_icon.png"  # Foreground for adaptive icons
